# Image Rotation and Translation

In [2]:
import cv2
import numpy as ns

In [3]:
read=cv2.imread("C:/Users/shiya/Downloads/th.jpeg")

In [4]:
read

array([[[ 31,  63,  68],
        [ 29,  64,  68],
        [ 29,  64,  67],
        ...,
        [  2,  57, 114],
        [  3,  63, 117],
        [  8,  70, 124]],

       [[ 30,  62,  67],
        [ 30,  62,  67],
        [ 29,  64,  67],
        ...,
        [  0,  53, 108],
        [  1,  58, 113],
        [  5,  65, 119]],

       [[ 31,  62,  65],
        [ 30,  63,  66],
        [ 29,  64,  67],
        ...,
        [  0,  47, 103],
        [  0,  52, 107],
        [  1,  59, 111]],

       ...,

       [[ 18, 127, 179],
        [ 16, 125, 177],
        [ 13, 123, 175],
        ...,
        [ 11,  65, 130],
        [  8,  66, 132],
        [ 10,  70, 136]],

       [[ 19, 128, 180],
        [ 18, 127, 179],
        [ 16, 126, 178],
        ...,
        [ 10,  64, 129],
        [  9,  67, 133],
        [ 12,  72, 138]],

       [[ 21, 130, 182],
        [ 20, 129, 181],
        [ 18, 128, 180],
        ...,
        [ 10,  64, 129],
        [ 10,  68, 134],
        [ 15,  75, 141]]

In [5]:
shp=read.shape

In [6]:
shp

(180, 240, 3)

In [7]:
h,w=read.shape[:2]
print(h)
print(w)

180
240


In [8]:
center=h/2,w/2

In [9]:
center

(90.0, 120.0)

# Rotation Matrix

In [10]:
rotate_matrix=cv2.getRotationMatrix2D(center=center,angle=60,scale=0.5)

In [11]:
rotate_matrix

array([[  0.25      ,   0.4330127 ,  15.53847577],
       [ -0.4330127 ,   0.25      , 128.97114317]])

In [12]:
rotated_image=cv2.warpAffine(src=read,M=rotate_matrix,dsize=(h,w))

In [13]:
cv2.imshow("original image",read)
cv2.waitKey(0)
cv2.imshow("rotated image",rotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Translation Matrix

In [14]:
trans_x,trans_y=w/2,h/2

In [27]:
trans_matrix=ns.array([[0.5,0,trans_x],[0,0.5,trans_y]])

In [28]:
trans_matrix

array([[  0.5,   0. , 120. ],
       [  0. ,   0.5,  90. ]])

In [29]:
trans_image=cv2.warpAffine(src=read,M=trans_matrix,dsize=(h,w))

In [30]:
cv2.imshow("trans_image",trans_image)
cv2.waitKey(0)
cv2.destroyAllWindows()